#!/bin/bash
STAGED_FILES=$(git diff --name-only --diff-filter=ACM HEAD^..HEAD | grep -E ".*js\/modules.*\.jsx?")

if [[ "$STAGED_FILES" = "" ]]; then
  echo -e "\n[No Javascript to validate]\n"
  exit 0
fi

PASS=true

echo -e "\nValidating Javascript:\n"

for FILE in $STAGED_FILES
do
  node ./node_modules/eslint/bin/eslint.js "$FILE"

  if [[ "$?" == 0 ]]; then
    echo -e "\t\033[32mESLint Passed: $FILE\033[0m"
  else
    echo -e "\t\033[41mESLint Failed: $FILE\033[0m"
    PASS=false
  fi
done

echo -e "\nJavascript validation completed!\n"

if ! $PASS; then
  echo -e "\033[41mFAILED:\033[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
  exit 1
else
  echo -e "\033[42mSUCCEEDED\033[0m\n"
fi

exit $?
